events { 
    worker_connections 1024; 
}

http {
    upstream backend_servers {
        # Round Robin es el algoritmo por defecto
        server web1:80;
        server web2:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_servers;
        }
    }
}
